/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ewi.server

import io.ktor.server.application.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import org.ewi.core.HelloWorld

object EWIServer {
    @JvmStatic
    fun main(args: Array<String>) {
        // Starts the Ktor server on port 8080 using Netty
        embeddedServer(Netty, port = 8080, host = "0.0.0.0", module = Application::module)
            .start(wait = true)
    }
}

// Extracting the module function keeps your server setup clean
fun Application.module() {
    routing {
        get("/") {
            call.respondText("EWIServer is running!")
        }
    }
}
