/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
    alias(libs.plugins.shadow)
    alias(libs.plugins.appengine)
}

dependencies {
    implementation(libs.ktor.server.call.logging)

    implementation("org.apache.commons:commons-text")
    implementation(project(":core"))
    
   // Server engine and core
    implementation(libs.ktor.server.core)
    implementation(libs.ktor.server.netty)
    
    // Auth features
    implementation(libs.ktor.server.auth)
    implementation(libs.ktor.server.auth.jwt)
    
    // JSON & Serialization
    implementation(libs.ktor.server.content.negotiation)
    implementation(libs.ktor.serialization.kotlinx.json)
    
    // Logging
    implementation(libs.logback.classic)
}

application {
    // Define the main class for the application.
    mainClass = "org.ewi.server.EWIServer"
}

// App Engine specific configuration
appengine {
    
    stage {
        setArtifact(layout.buildDirectory.file("libs/EWIServer.jar").get().asFile)
    }

    deploy {
        projectId = "elevate-water-foundation" // Picks up project from gcloud CLI
        version = "alpha-001"
    }
}

tasks.named<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>("shadowJar") {
    mergeServiceFiles()
    archiveFileName.set("EWIServer.jar")
    
    manifest {
        attributes["Main-Class"] = "org.ewi.server.EWIServer"
    }
}
