/*
 * This file was generated by the Gradle 'init' task.
 */
import org.apache.tools.ant.taskdefs.condition.Os // <-- CRITICAL: Required for OS check

plugins {
    id("buildlogic.kotlin-application-conventions")
    alias(libs.plugins.shadow)
    alias(libs.plugins.appengine)
}

dependencies {
    implementation(libs.ktor.server.call.logging)

    implementation("org.apache.commons:commons-text")
    implementation(project(":core"))
    
   // Server engine and core
    implementation(libs.ktor.server.core)
    implementation(libs.ktor.server.netty)
    
    // Auth features
    implementation(libs.ktor.server.auth)
    implementation(libs.ktor.server.auth.jwt)
    
    // JSON & Serialization
    implementation(libs.ktor.server.content.negotiation)
    implementation(libs.ktor.serialization.kotlinx.json)
    
    // Logging
    implementation(libs.logback.classic)

    // Firebase
    // Firebase Admin SDK for token verification
    implementation(libs.firebase.admin)
    
    // Google Auth for service account handling in App Engine
    implementation(libs.google.auth.library)

    // Compression
    implementation(libs.ktor.server.compression)
    implementation(libs.ktor.server.compression.zstd)
}

application {
    // Define the main class for the application.
    mainClass = "org.ewi.server.EWIServer"
}

// App Engine specific configuration
appengine {
    stage {
        setArtifact(layout.buildDirectory.file("libs/EWIServer.jar").get().asFile)
    }

    deploy {
        projectId = "elevate-water-foundation" // Picks up project from gcloud CLI
        version = "alpha-013"
    }
}

tasks.named<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>("shadowJar") {
    mergeServiceFiles()
    archiveFileName.set("EWIServer.jar")
    
    manifest {
        attributes["Main-Class"] = "org.ewi.server.EWIServer"
    }
}

// =========================================================
// VITE FRONTEND INTEGRATION
// =========================================================

// 1. Define npm command based on OS
val npmCommand = if (Os.isFamily(Os.FAMILY_WINDOWS)) "npm.cmd" else "npm"

// 2. Create Install Task First
val installFrontend by tasks.registering(Exec::class) {
    group = "build"
    description = "Installs frontend dependencies via npm"
    workingDir = rootProject.file("frontend") 
    commandLine(npmCommand, "install")
}

// 3. Create Build Task Second
val buildFrontend by tasks.registering(Exec::class) {
    group = "build"
    description = "Builds the Vite frontend via npm"
    dependsOn(installFrontend)
    workingDir = rootProject.file("frontend")
    commandLine(npmCommand, "run", "build")
}

// 4. Hook into processResources (which ShadowJar and AppEngine rely on)
tasks.named<ProcessResources>("processResources") {
    // Tell Gradle to wait for Vite to finish building
    dependsOn(buildFrontend)
    
    // Grab the dist folder relative to the root project
    from(rootProject.file("frontend/dist")) {
        // Put it into a 'static' folder inside the Ktor JAR
        into("static") 
    }
}

// 5. Ensure it runs before App Engine deployment (just to be absolutely safe)
tasks.matching { it.name == "appengineDeploy" }.configureEach {
    dependsOn(buildFrontend)
}

// =========================================================
// FIREBASE FUNCTIONS INTEGRATION
// =========================================================

// Helper to run npm commands cross-platform
fun Exec.npm(vararg args: String) {
    if (Os.isFamily(Os.FAMILY_WINDOWS)) {
        commandLine("cmd", "/c", "npm", *args)
    } else {
        // This 'sh -c' approach is much more reliable on macOS
        commandLine("sh", "-c", "npm ${args.joinToString(" ")}")
    }
}

val installFunctionsDeps by tasks.registering(Exec::class) {
    group = "build"
    // Use rootProject.file to ensure we go to the actual functions directory
    workingDir = rootProject.file("functions") 
    npm("install")
}

val buildFunctions by tasks.registering(Exec::class) {
    group = "build"
    dependsOn(installFunctionsDeps)
    workingDir = rootProject.file("functions")
    npm("run", "build")
}

// Ensure the main build task triggers this
tasks.named("build") {
    dependsOn(buildFunctions)
}