/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ewi.app

import io.ktor.server.application.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*
import io.ktor.server.response.*
import io.ktor.server.routing.*
import org.ewi.core.HelloWorld

fun main() {
    embeddedServer(Netty, port = 8080) {
        routing {
            get("/") {
                call.respondText(HelloWorld.message)
            }
        }
    }.start(wait = true)
}
